# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.16
      - uses: syphar/restore-virtualenv@v1
        id: cache-gs
        with:
          requirement_files: setup.cfg
      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-gs.outputs.cache-hit != 'true'
      - name: Install Geosample
        run: |
          pip install .[tests]
        if: steps.cache-gs.outputs.cache-hit != 'true'
      - name: Unittests
        run: |
          python -m unittest
